\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=2.54cm]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Assignment 6: Generalized Linear Models},
            pdfauthor={Yifei Zhang},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Assignment 6: Generalized Linear Models}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Yifei Zhang}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\subsection{OVERVIEW}\label{overview}

This exercise accompanies the lessons in Environmental Data Analytics
(ENV872L) on generalized linear models.

\subsection{Directions}\label{directions}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Use the lesson as a guide. It contains code that can be modified to
  complete the assignment.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
  Space for your answers is provided in this document and is indicated
  by the ``\textgreater{}'' character. If you need a second paragraph be
  sure to start the first line with ``\textgreater{}''. You should
  notice that the answer is highlighted in green by RStudio.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file. You will need to have the correct
  software installed to do this (see Software Installation Guide) Press
  the \texttt{Knit} button in the RStudio scripting panel. This will
  save the PDF output in your Assignments folder.
\item
  After Knitting, please submit the completed exercise (PDF file) to the
  dropbox in Sakai. Please add your last name into the file name (e.g.,
  ``Salk\_A06\_GLMs.pdf'') prior to submission.
\end{enumerate}

The completed exercise is due on Tuesday, 26 February, 2019 before class
begins.

\subsection{Set up your session}\label{set-up-your-session}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Set up your session. Upload the EPA Ecotox dataset for Neonicotinoids
  and the NTL-LTER raw data file for chemistry/physics.
\item
  Build a ggplot theme and set it as your default theme.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#1}
\KeywordTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/Users/yifeizhang/R/Environmental Data Analytics"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages ---------------------------------------------------------- tidyverse 1.2.1 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.1.0     v purrr   0.2.5
## v tibble  2.0.1     v dplyr   0.7.8
## v tidyr   0.8.2     v stringr 1.3.1
## v readr   1.3.1     v forcats 0.3.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(colormap)}
\NormalTok{EPAEcotox <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/ECOTOX_Neonicotinoids_Mortality_raw.csv"}\NormalTok{)}
\NormalTok{NTL_LTER_Lake <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/NTL-LTER_Lake_ChemistryPhysics_Raw.csv"}\NormalTok{)}
\CommentTok{#2}
\NormalTok{Yifeitheme <-}\StringTok{ }\KeywordTok{theme_light}\NormalTok{(}\DataTypeTok{base_size =} \DecValTok{14}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{color =} \StringTok{"black"}\NormalTok{), }
        \DataTypeTok{legend.position =} \StringTok{"right"}\NormalTok{)}
\KeywordTok{theme_set}\NormalTok{(Yifeitheme)}
\end{Highlighting}
\end{Shaded}

\subsection{Neonicotinoids test}\label{neonicotinoids-test}

Research question: Were studies on various neonicotinoid chemicals
conducted in different years?

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
  Generate a line of code to determine how many different chemicals are
  listed in the Chemical.Name column.
\item
  Are the publication years associated with each chemical
  well-approximated by a normal distribution? Run the appropriate test
  and also generate a frequency polygon to illustrate the distribution
  of counts for each year, divided by chemical name. Bonus points if you
  can generate the results of your test from a pipe function. No need to
  make this graph pretty.
\item
  Is there equal variance among the publication years for each chemical?
  Hint: var.test is not the correct function.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#3}
\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(EPAEcotox}\OperatorTok{$}\NormalTok{Chemical.Name))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#4}
\NormalTok{EPAEcotox }\OperatorTok{%>%}
\KeywordTok{group_by}\NormalTok{(Chemical.Name)}\OperatorTok{%>%}
\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{statistic=}\KeywordTok{shapiro.test}\NormalTok{(Pub..Year)}\OperatorTok{$}\NormalTok{statistic, }\DataTypeTok{p.value =} \KeywordTok{shapiro.test}\NormalTok{(Pub..Year)}\OperatorTok{$}\NormalTok{p.value)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 9 x 3
##   Chemical.Name statistic  p.value
##   <fct>             <dbl>    <dbl>
## 1 Acetamiprid       0.902 5.71e- 8
## 2 Clothianidin      0.696 4.29e-11
## 3 Dinotefuran       0.828 8.83e- 7
## 4 Imidacloprid      0.882 1.38e-22
## 5 Imidaclothiz      0.684 9.30e- 4
## 6 Nitenpyram        0.796 5.69e- 4
## 7 Nithiazine        0.759 1.24e- 4
## 8 Thiacloprid       0.767 1.12e-11
## 9 Thiamethoxam      0.707 1.57e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
  \KeywordTok{ggplot}\NormalTok{(EPAEcotox) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_freqpoly}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Pub..Year, }\DataTypeTok{color =}\NormalTok{ Chemical.Name)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_color_colormap}\NormalTok{(}\DataTypeTok{discrete =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{A06_GLMs_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#5}
  \KeywordTok{bartlett.test}\NormalTok{(EPAEcotox}\OperatorTok{$}\NormalTok{Pub..Year }\OperatorTok{~}\StringTok{ }\NormalTok{EPAEcotox}\OperatorTok{$}\NormalTok{Chemical.Name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Bartlett test of homogeneity of variances
## 
## data:  EPAEcotox$Pub..Year by EPAEcotox$Chemical.Name
## Bartlett's K-squared = 139.59, df = 8, p-value < 2.2e-16
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Based on your results, which test would you choose to run to answer
  your research question?
\end{enumerate}

\begin{quote}
ANSWER: I would choose one-way ANOVA.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\item
  Run this test below.
\item
  Generate a boxplot representing the range of publication years for
  each chemical. Adjust your graph to make it pretty.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#7}
\NormalTok{PubYear.anova <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(EPAEcotox}\OperatorTok{$}\NormalTok{Pub..Year }\OperatorTok{~}\StringTok{ }\NormalTok{EPAEcotox}\OperatorTok{$}\NormalTok{Chemical.Name)}
\KeywordTok{summary}\NormalTok{(PubYear.anova)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = EPAEcotox$Pub..Year ~ EPAEcotox$Chemical.Name)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -18.366  -3.993   1.889   4.889  13.441 
## 
## Coefficients:
##                                      Estimate Std. Error  t value Pr(>|t|)
## (Intercept)                         2005.9926     0.6082 3298.222  < 2e-16
## EPAEcotox$Chemical.NameClothianidin    2.0479     1.0246    1.999  0.04584
## EPAEcotox$Chemical.NameDinotefuran    -3.4333     1.1057   -3.105  0.00194
## EPAEcotox$Chemical.NameImidacloprid    3.1181     0.6651    4.689 3.05e-06
## EPAEcotox$Chemical.NameImidaclothiz    6.4518     2.4412    2.643  0.00832
## EPAEcotox$Chemical.NameNitenpyram      7.7216     1.6630    4.643 3.78e-06
## EPAEcotox$Chemical.NameNithiazine    -17.6290     1.6299  -10.816  < 2e-16
## EPAEcotox$Chemical.NameThiacloprid     1.6394     0.9190    1.784  0.07467
## EPAEcotox$Chemical.NameThiamethoxam    4.3738     0.8261    5.295 1.40e-07
##                                        
## (Intercept)                         ***
## EPAEcotox$Chemical.NameClothianidin *  
## EPAEcotox$Chemical.NameDinotefuran  ** 
## EPAEcotox$Chemical.NameImidacloprid ***
## EPAEcotox$Chemical.NameImidaclothiz ** 
## EPAEcotox$Chemical.NameNitenpyram   ***
## EPAEcotox$Chemical.NameNithiazine   ***
## EPAEcotox$Chemical.NameThiacloprid  .  
## EPAEcotox$Chemical.NameThiamethoxam ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 7.093 on 1274 degrees of freedom
## Multiple R-squared:  0.1726, Adjusted R-squared:  0.1674 
## F-statistic: 33.21 on 8 and 1274 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PubYear.anova2 <-}\StringTok{ }\KeywordTok{aov}\NormalTok{(EPAEcotox}\OperatorTok{$}\NormalTok{Pub..Year }\OperatorTok{~}\StringTok{ }\NormalTok{EPAEcotox}\OperatorTok{$}\NormalTok{Chemical.Name)}
\KeywordTok{summary}\NormalTok{(PubYear.anova2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                           Df Sum Sq Mean Sq F value Pr(>F)    
## EPAEcotox$Chemical.Name    8  13365  1670.7   33.21 <2e-16 ***
## Residuals               1274  64093    50.3                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{TukeyHSD}\NormalTok{(PubYear.anova2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = EPAEcotox$Pub..Year ~ EPAEcotox$Chemical.Name)
## 
## $`EPAEcotox$Chemical.Name`
##                                  diff          lwr           upr     p adj
## Clothianidin-Acetamiprid    2.0478935  -1.13556203   5.231348994 0.5444735
## Dinotefuran-Acetamiprid    -3.4333250  -6.86887521   0.002225165 0.0502982
## Imidacloprid-Acetamiprid    3.1181443   1.05175043   5.184538190 0.0001059
## Imidaclothiz-Acetamiprid    6.4517974  -1.13341497  14.037009746 0.1700689
## Nitenpyram-Acetamiprid      7.7216387   2.55455876  12.888718547 0.0001312
## Nithiazine-Acetamiprid    -17.6290107 -22.69334307 -12.564678323 0.0000000
## Thiacloprid-Acetamiprid     1.6394284  -1.21592420   4.494781028 0.6929485
## Thiamethoxam-Acetamiprid    4.3738126   1.80714109   6.940484045 0.0000050
## Dinotefuran-Clothianidin   -5.4812185  -9.32765358  -1.634783428 0.0003529
## Imidacloprid-Clothianidin   1.0702508  -1.62456668   3.765068330 0.9489438
## Imidaclothiz-Clothianidin   4.4039039  -3.37603853  12.183846336 0.7094335
## Nitenpyram-Clothianidin     5.6737452   0.22482121  11.122669133 0.0338611
## Nithiazine-Clothianidin   -19.6769042 -25.02849460 -14.325313751 0.0000000
## Thiacloprid-Clothianidin   -0.4084651  -3.74689228   2.929962144 0.9999879
## Thiamethoxam-Clothianidin   2.3259191  -0.76921583   5.421054007 0.3218154
## Imidacloprid-Dinotefuran    6.5514693   3.56304877   9.539889900 0.0000000
## Imidaclothiz-Dinotefuran    9.8851224   1.99867071  17.771574107 0.0033119
## Nitenpyram-Dinotefuran     11.1549637   5.55501829  16.754909074 0.0000000
## Nithiazine-Dinotefuran    -14.1956857 -19.70096824  -8.690403099 0.0000000
## Thiacloprid-Dinotefuran     5.0727534   1.49312883   8.652378050 0.0003937
## Thiamethoxam-Dinotefuran    7.8071376   4.45326278  11.161012409 0.0000000
## Imidaclothiz-Imidacloprid   3.3336531  -4.05979665  10.727102808 0.8976481
## Nitenpyram-Imidacloprid     4.6034943  -0.27773162   9.484720319 0.0825706
## Nithiazine-Imidacloprid   -20.7471550 -25.51948303 -15.974826981 0.0000000
## Thiacloprid-Imidacloprid   -1.4787159  -3.77669129   0.819259503 0.5440493
## Thiamethoxam-Imidacloprid   1.2556683  -0.67188326   3.183219776 0.5266734
## Nitenpyram-Imidaclothiz     1.2698413  -7.51035405  10.050036590 0.9999561
## Nithiazine-Imidaclothiz   -24.0808081 -32.80093294 -15.360683218 0.0000000
## Thiacloprid-Imidaclothiz   -4.8123690 -12.46391482   2.839176871 0.5758935
## Thiamethoxam-Imidaclothiz  -2.0779848  -9.62655539   5.470585757 0.9950400
## Nithiazine-Nitenpyram     -25.3506494 -32.07402988 -18.627268825 0.0000000
## Thiacloprid-Nitenpyram     -6.0822102 -11.34618420  -0.818236282 0.0103350
## Thiamethoxam-Nitenpyram    -3.3478261  -8.46096463   1.765312458 0.5194316
## Thiacloprid-Nithiazine     19.2684391  14.10528410  24.431594116 0.0000000
## Thiamethoxam-Nithiazine    22.0028233  16.99353853  27.012107998 0.0000000
## Thiamethoxam-Thiacloprid    2.7343842  -0.02215529   5.490923603 0.0538087
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#8}
\KeywordTok{ggplot}\NormalTok{(EPAEcotox, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Chemical.Name, }\DataTypeTok{y =}\NormalTok{ Pub..Year))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_boxplot}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{""}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Publication Year"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{,  }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{A06_GLMs_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  How would you summarize the conclusion of your analysis? Include a
  sentence summarizing your findings and include the results of your
  test in parentheses at the end of the sentence.
\end{enumerate}

\begin{quote}
ANSWER: The publication years associated with these 9 different
chemicals are relatively different(ANOVA; df=1274, F=33.21,
p\textless{}0.0001)
\end{quote}

\subsection{NTL-LTER test}\label{ntl-lter-test}

Research question: What is the best set of predictors for lake
temperatures in July across the monitoring period at the North Temperate
Lakes LTER?

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Wrangle your NTL-LTER dataset with a pipe function so that it contains
  only the following criteria:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Only dates in July (hint: use the daynum column). No need to consider
  leap years.
\item
  Only the columns: lakename, year4, daynum, depth, temperature\_C
\item
  Only complete cases (i.e., remove NAs)
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  Run an AIC to determine what set of explanatory variables (year4,
  daynum, depth) is best suited to predict temperature. Run a multiple
  regression on the recommended set of variables.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#11}
\NormalTok{NTL_LTER_Tidy <-NTL_LTER_Lake }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(daynum}\OperatorTok{>=}\DecValTok{183} \OperatorTok{&}\StringTok{ }\NormalTok{daynum}\OperatorTok{<=}\DecValTok{213}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(lakename, year4, daynum, depth, temperature_C)}\OperatorTok{%>%}
\StringTok{  }\NormalTok{na.omit}
\CommentTok{#12}
\NormalTok{TempAIC <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_LTER_Tidy, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{year4 }\OperatorTok{+}\StringTok{ }\NormalTok{daynum }\OperatorTok{+}\StringTok{ }
\StringTok{              }\NormalTok{depth)}
\KeywordTok{step}\NormalTok{(TempAIC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=25998.22
## temperature_C ~ year4 + daynum + depth
## 
##          Df Sum of Sq    RSS   AIC
## <none>                142056 25998
## - year4   1       201 142257 26010
## - daynum  1      1237 143293 26080
## - depth   1    402549 544605 38995
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ year4 + daynum + depth, data = NTL_LTER_Tidy)
## 
## Coefficients:
## (Intercept)        year4       daynum        depth  
##   -18.19700      0.01611      0.04024     -1.94133
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{TempModel <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_LTER_Tidy, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{year4 }\OperatorTok{+}\StringTok{ }\NormalTok{daynum }\OperatorTok{+}\StringTok{ }\NormalTok{depth)}
\KeywordTok{summary}\NormalTok{(TempModel)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ year4 + daynum + depth, data = NTL_LTER_Tidy)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.6857 -3.0267  0.1055  2.9937 13.6038 
## 
## Coefficients:
##               Estimate Std. Error  t value Pr(>|t|)    
## (Intercept) -18.196998   8.741236   -2.082 0.037392 *  
## year4         0.016113   0.004353    3.701 0.000216 ***
## daynum        0.040237   0.004385    9.176  < 2e-16 ***
## depth        -1.941328   0.011728 -165.528  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.833 on 9669 degrees of freedom
## Multiple R-squared:  0.7398, Adjusted R-squared:  0.7397 
## F-statistic:  9162 on 3 and 9669 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  What is the final linear equation to predict temperature from your
  multiple regression? How much of the observed variance does this model
  explain?
\end{enumerate}

\begin{quote}
ANSWER: The final linear equation is temperature\_C = 0.016year4 +
0.04daynum - 1.94depth -18.2, this model explains 74\% of the observed
variance.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  Run an interaction effects ANCOVA to predict temperature based on
  depth and lakename from the same wrangled dataset.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#14}
\NormalTok{Temp_ancova.interaction <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_LTER_Tidy, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{lakename }\OperatorTok{*}\StringTok{ }\NormalTok{depth)}
\KeywordTok{summary}\NormalTok{(Temp_ancova.interaction)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ lakename * depth, data = NTL_LTER_Tidy)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.683 -2.907 -0.290  2.795 16.336 
## 
## Coefficients:
##                                Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                     22.8748     0.5657  40.435  < 2e-16 ***
## lakenameCrampton Lake            2.5625     0.6516   3.932 8.47e-05 ***
## lakenameEast Long Lake          -4.2925     0.5992  -7.164 8.40e-13 ***
## lakenameHummingbird Lake        -2.6059     0.8262  -3.154  0.00161 ** 
## lakenamePaul Lake                0.7623     0.5787   1.317  0.18779    
## lakenamePeter Lake               0.4321     0.5773   0.749  0.45412    
## lakenameTuesday Lake            -2.8349     0.5862  -4.836 1.35e-06 ***
## lakenameWard Lake                2.4887     0.8298   2.999  0.00271 ** 
## lakenameWest Long Lake          -2.3347     0.5974  -3.908 9.36e-05 ***
## depth                           -2.5543     0.2330 -10.962  < 2e-16 ***
## lakenameCrampton Lake:depth      0.7704     0.2379   3.239  0.00121 ** 
## lakenameEast Long Lake:depth     0.9181     0.2352   3.903 9.57e-05 ***
## lakenameHummingbird Lake:depth  -0.5692     0.2879  -1.977  0.04809 *  
## lakenamePaul Lake:depth          0.3698     0.2341   1.580  0.11417    
## lakenamePeter Lake:depth         0.5495     0.2338   2.350  0.01878 *  
## lakenameTuesday Lake:depth       0.6462     0.2345   2.755  0.00587 ** 
## lakenameWard Lake:depth         -0.7207     0.2795  -2.578  0.00995 ** 
## lakenameWest Long Lake:depth     0.7870     0.2351   3.347  0.00082 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.474 on 9655 degrees of freedom
## Multiple R-squared:  0.7865, Adjusted R-squared:  0.7861 
## F-statistic:  2093 on 17 and 9655 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{14}
\tightlist
\item
  Is there an interaction between depth and lakename? How much variance
  in the temperature observations does this explain?
\end{enumerate}

\begin{quote}
ANSWER: Except for Paul lake, there is an interaction between depth and
lakename. This explains 78.6\% of the variance in the temperature
observations.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{15}
\tightlist
\item
  Create a graph that depicts temperature by depth, with a separate
  color for each lake. Add a geom\_smooth (method = ``lm'', se = FALSE)
  for each lake. Make your points 50 \% transparent. Adjust your y axis
  limits to go from 0 to 35 degrees. Clean up your graph to make it
  pretty.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#16}
\NormalTok{Plot16 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(NTL_LTER_Tidy, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ temperature_C, }\DataTypeTok{x =}\NormalTok{ depth, }\DataTypeTok{color =}\NormalTok{ lakename))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.5}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{35}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"Depth(m)"}\NormalTok{, }\DataTypeTok{y=} \StringTok{"Temperature ("}\OperatorTok{~}\NormalTok{degree}\OperatorTok{~}\StringTok{"C)"}\NormalTok{, }\DataTypeTok{color =} \StringTok{"Lake Name"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_color_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{c}\NormalTok{(}\StringTok{'#e41a1c'}\NormalTok{,}\StringTok{'#377eb8'}\NormalTok{,}\StringTok{'#4daf4a'}\NormalTok{,}\StringTok{'#984ea3'}\NormalTok{,}\StringTok{'#ff7f00'}\NormalTok{,}\StringTok{'#ffff33'}\NormalTok{,}\StringTok{'#a65628'}\NormalTok{,}\StringTok{'#f781bf'}\NormalTok{,}\StringTok{'#999999'}\NormalTok{))}
\KeywordTok{print}\NormalTok{(Plot16)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 72 rows containing missing values (geom_smooth).
\end{verbatim}

\includegraphics{A06_GLMs_files/figure-latex/unnamed-chunk-6-1.pdf}


\end{document}
